Repository spring-projects/spring-kafka, pull requests merged in 2023-05, with the labels that each got.

#2667 Expose user exception thrown during rebalance
  spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareRebalanceListener.java
Labels: type: task

#2681 Upgrade Spring Data, Micrometer Versions
  .vscode/settings.json
  build.gradle
Labels: type: dependency-upgrade

#2684 docs: fix name of overriden method
  spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
Labels: type: documentation
