Repository spring-projects/spring-kafka, pull requests merged in 2023-11, with the labels that each got.

#2873 some cosmetic improvements of the reference - part 2
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/events.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/annotation-send-to.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/filtering.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-annotation.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-group-id.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listeners.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/rebalance-listeners.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/sequencing.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/template-receive.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/seek.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
  spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/dynamic/Application.java
Labels: type: documentation

#2877 cosmetic doc improvements part 3
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-factory.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/exactly-once.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/headers.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/interceptors.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/pause-resume-partitions.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/producer-interceptor-managed-in-spring.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/tombstones.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/transactions.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/how-the-pattern-works.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/programmatic-construction.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-config.adoc
  spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/started/noboot/Config.java
Labels: type: documentation

#2880 update reference documentation gradle task in README.md
  README.md
Labels: type: documentation

#2881 fix CONSUMER_RECORDS_CLASS_NAME constant error in KafkaAvroBeanRegistrationAotProcessor.java
  spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaAvroBeanRegistrationAotProcessor.java
Labels: type: bug, Backport 3.0.x

#2874 ProducerInterceptor in KafkaTempalte unvaild
  spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
  spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
Labels: type: bug, Backport 3.0.x

#2879 cosmetic doc improvements part 4
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/native-images.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/exactly-once.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/headers.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/quick-tour.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/accessing-delivery-attempts.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/dlt-strategies.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/features.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-topic-combine-blocking.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-topic-lcf.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/topic-naming.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Labels: type: documentation

#2885 fix some typos
  spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/ContainerTestUtils.java
  spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
  spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
  spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
  spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
  spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerPartitionNoLongerIdleEvent.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/BatchAcknowledgingConsumerAwareMessageListener.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
  spring-kafka/src/main/java/org/springframework/kafka/mock/MockConsumerFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicHeaders.java
  spring-kafka/src/main/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandler.java
  spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessageConverter.java
  spring-kafka/src/main/java/org/springframework/kafka/support/serializer/RetryingDeserializer.java
Labels: type: documentation

#2893 remove unnecessary property setting statement in EmbeddedKafkaKraftBroker
  spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
Labels: type: enhancement

#2899 fix a bug in RoutingKafkaTemplate
  spring-kafka/src/main/java/org/springframework/kafka/core/RoutingKafkaTemplate.java
  spring-kafka/src/test/java/org/springframework/kafka/core/RoutingKafkaTemplateTests.java
Labels: type: bug

#2876 GH-2654: Incorrect retry topic suffix
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
  spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryTopicConfigurationProvider.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactory.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Labels: type: enhancement

#2910 Upgrade Dependency Versions
  build.gradle
Labels: type: dependency-upgrade

#2911 Upgrade Dependency Versions
  build.gradle
Labels: type: dependency-upgrade
