Repository spring-projects/spring-kafka, pull requests merged in 2023-04, with the labels that each got.

#2656 Upgrade Spring Framework, Data, Reactor, Micrometer Versions
  build.gradle
Labels: type: dependency-upgrade

#2657 Upgrade Spring Framework, Data, Micrometer, Reactor, JUnit Versions
  .gitignore
  build.gradle
Labels: type: dependency-upgrade

#2659 Remove duplicate native hint registration.
  spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
Labels: type: enhancement

#2661 Fix Race in Micrometer Test
  spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Labels: type: bug, backport 2.9.x

#2670 Howewever -> However
  spring-kafka-docs/src/main/asciidoc/tips.adoc
Labels: type: documentation
