Repository spring-projects/spring-kafka, pull requests merged in 2023-06, with the labels that each got.

#2691 docs: fix Javadoc of CommonErrorHandler::remainingRecords
  spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
Labels: type: documentation

#2700 Default Empty Map for PF configurationProperties
  spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
Labels: type: bug

#2703 MMConverter Support Custom Partition Selection
  spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
  spring-kafka/src/test/java/org/springframework/kafka/support/converter/MessagingMessageConverterTests.java
Labels: type: enhancement

#2710 Upgrade Spring Framework, Data, Retry, Micrometer, Reactor Versions
  build.gradle
Labels: type: dependency-upgrade
