Repository spring-projects/spring-kafka, pull requests merged in 2023-10, with the labels that each got.

#2822 Get rid of proxy in DefaultKafkaConsumerFactory
  spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
  spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
Labels: type: enhancement

#2827 Upgrade to Apache Kafka 3.6.0
  build.gradle
Labels: type: dependency-upgrade

#2844 Document Using Kafka 3.6.0 With This Version
  spring-kafka-docs/src/main/asciidoc/appendix.adoc
Labels: type: documentation

#2845 Upgrade Micrometer, Reactor, Spring Data Versions
  build.gradle
Labels: type: dependency-upgrade

#2846 Upgrade Spring Framework, Data, Micrometer Reactor
  build.gradle
Labels: type: dependency-upgrade

#2847 Upgrade Dependency Versions
  build.gradle
Labels: type: dependency-upgrade

#2849 Add kafka-server-common Transitive Test Dependency
  build.gradle
Labels: type: task

#2850 Add kafka-server-common Transitive Test Dependency
  build.gradle
Labels: type: task

#2871 Update streams.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
Labels: type: documentation

#2869 GH-2862: Add Option to Log Recovery to DLPR
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
  spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/support/serializer/SerializationUtils.java
Labels: type: enhancement
