Repository spring-projects/spring-kafka, pull requests merged in 2024-10, with the labels that each got.

#3545 Remove dead code from test codes.
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Labels: type: improvement

#3551 No Issue : Refactor test codes and Remove useless full package name.
  spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
  spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ExistingRetryTopicClassLevelIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ExistingRetryTopicIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelExceptionRoutingIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicSameContainerFactoryIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/streams/Configurer1Tests.java
  spring-kafka/src/test/java/org/springframework/kafka/streams/Configurer2Tests.java
  spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsBranchTests.java
  spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsInteractiveQueryServiceTests.java
  spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsJsonSerializationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
  spring-kafka/src/test/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandlerTests.java
Labels: type: improvement

#3550 Refactor ProducerFactory to use constant for repeated exception message
  spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
Labels: type: improvement

#3556 Improve warning message for ConsumerRecords filter strategy
  spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
Labels: type: improvement

#3561 Add `TaskScheduler` option for Kafka metrics components
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
  spring-kafka/src/main/java/org/springframework/kafka/core/KafkaMetricsSupport.java
  spring-kafka/src/main/java/org/springframework/kafka/core/MicrometerConsumerListener.java
  spring-kafka/src/main/java/org/springframework/kafka/core/MicrometerProducerListener.java
  spring-kafka/src/main/java/org/springframework/kafka/streams/KafkaStreamsMicrometerListener.java
  spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
  spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
Labels: type: enhancement

#3563 Fix flaky tests in async retry by using a latch instead of sleep.
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/AsyncCompletableFutureRetryTopicScenarioTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/AsyncMonoRetryTopicScenarioTests.java
Labels: type: task

#3559 Improve the implementation of the toMessage() function in the BatchMessagingMessageConverter:
  spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
Labels: type: improvement

#3588 Refine docs for consistency and correctness
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
  spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
Labels: type: documentation

#3604 Refine docs for improved accuracy
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/events.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/annotation-send-to.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
Labels: type: documentation

#3603 Update LogAccessor instantiations with current class names
  spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerPartitionPausingBackOffManager.java
  spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerialization.java
Labels: type: improvement

#3606 Update broken Git documentation link to correct URL
  CONTRIBUTING.adoc
Labels: type: documentation

#3605 Remove duplicate producerProperties declaration in kafkaProducerFactory
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/interceptors.adoc
Labels: type: documentation
