Repository spring-projects/spring-kafka, pull requests merged in 2024-03, with the labels that each got.

#3091 fix bug at KafkaMessageListenerContainerTests.testInvokeRecordInterceptorAllSkipped()
  spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Labels: for: backport-to-3.1.x

#3090 Polish KafkaMessageListenerContainer
  spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Labels: type: enhancement

#3106 Correct class naming convention for 'hat' in serializer/deserializer Doc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
Labels: type: enhancement, type: documentation

#3104 polish retryable topic.
  spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
  spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
  spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/support/EndpointHandlerMethod.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupportTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java
Labels: type: enhancement

#3107 @RetryableTopic support @KafkaListener annotated on class part 1
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-config.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
  spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryTopicConfigurationProvider.java
  spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
  spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicAnnotationProcessorTests.java
Labels: type: enhancement

#3112 @RetryableTopic support KL annotated on class part 2
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
  spring-kafka/src/main/java/org/springframework/kafka/config/MultiMethodKafkaListenerEndpoint.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizer.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
  spring-kafka/src/main/java/org/springframework/kafka/support/EndpointHandlerMethod.java
  spring-kafka/src/main/java/org/springframework/kafka/support/EndpointHandlerMultiMethod.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactoryTests.java
  spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
Labels: type: enhancement

#3144 fix typo in JsonDeSerializer.TYPE_MAPPINGS
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
Labels: type: documentation

#3147 Remove org.apache.kafka native runtime hints
  spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
Labels: type: enhancement

#3168 Add an option to leave consumer group when closing Streams
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
  spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
Labels: type: enhancement
