Repository spring-projects/spring-kafka, pull requests merged in 2024-02, with the labels that each got.

#3016 Remove AbstractMessageListenerContainer.isPaused
  spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
  spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Labels: type: enhancement

#3033 Clarify retries in KSIQS docs
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
Labels: type: documentation

#3047 Enhanced monitoring when KMLC is batch listener
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
  spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Labels: type: bug, for: backport-to-3.1.x

#3053 GH-2287: Align RecordInterceptor and BatchInterceptor lifecycle.
  spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
  spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Labels: type: enhancement, for: backport-to-3.1.x

#3059 Fix TestOOMError#testOOMCMLC throw ConcurrentModificationException
  spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java
Labels: type: enhancement, for: backport-to-3.1.x

#3065 Polish KafkaTemplate
  spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
Labels: type: enhancement

#3079 Polish KafkaMessageListenerContainer
  spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Labels: type: enhancement

#3077 Deprecation Code Cleanup
  spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
  spring-kafka/src/test/java/org/springframework/kafka/listener/FailedBatchProcessorTests.java
  spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
  spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Labels: type: task

#3072 Non-Blocking Retries cannot combine with container transactions.
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/transactions.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic.adoc
Labels: type: documentation, for: backport-to-3.0.x, for: backport-to-3.1.x

#3081 Fix race condition at TransactionalContainerTests.testBatchListenerRecoverAfterRollbackProcessorCrash
  spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Labels: type: enhancement
