Repository spring-projects/spring-kafka, pull requests merged in 2025-05, with the labels that each got.

#3885 GH-3712: Make ContainerPausingBackOffHandler working in batch mode.
  spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
  spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
Labels: type: bug, for: backport-to-3.2.x, for: backport-to-3.3.x

#3909 Rephrase replication factor documentation
  spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
  spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
Labels: for: backport-to-3.2.x, for: backport-to-3.3.x

#3929 Altered the example in EmbeddedKafkaHolder usage
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Labels: for: backport-to-3.2.x, for: backport-to-3.3.x

#3923 Introduce share consumer factories for Kafka Queues (Early Access)
  spring-kafka/src/main/java/org/springframework/kafka/core/DefaultShareConsumerFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/core/ShareConsumerFactory.java
  spring-kafka/src/test/java/org/springframework/kafka/core/DefaultShareConsumerFactoryTests.java
Labels: type: enhancement

#3936 Remove ConsumerRebalanceProtocolTests
  spring-kafka/src/test/java/org/springframework/kafka/listener/ConsumerRebalanceProtocolTests.java
Labels: type: improvement
