Repository spring-projects/spring-kafka, pull requests merged in 2025-02, with the labels that each got.

#3736 Fix typo in `CONTRIBUTING` and `README`
  README.md
Labels: type: documentation

#3737 Add jspecify based Nullability checks in spring-kafka-test module
  spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/assertj/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerFactory.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/context/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/core/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/hamcrest/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/junit/GlobalEmbeddedKafkaTestExecutionListener.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/junit/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/package-info.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/ContainerTestUtils.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
  spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/package-info.java
  src/checkstyle/checkstyle.xml
Labels: type: enhancement

#3760 Fixing race condition in MicrometerMetricsTests
  spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/MicrometerMetricsTests.java
Labels: type: bug, for: backport-to-3.3.x

#3769 Update version antora for branch docs-build
  antora-playbook.yml
  build.gradle
Labels: type: enhancement

#3768 Improve `build.gradle` for building antora
  gradle/docs.gradle
  spring-kafka-docs/src/main/antora/antora-playbook.yml
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/native-images.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/filtering.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-annotation.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/tombstones.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/other-resources.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/quick-tour.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Labels: type: enhancement

#3770 Fix block code in section Examples
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
Labels: type: enhancement

#3771 Polishing
  spring-kafka/src/main/java/org/springframework/kafka/annotation/DltHandler.java
  spring-kafka/src/main/java/org/springframework/kafka/support/Suffixer.java
Labels: type: enhancement
