Repository spring-projects/spring-kafka, pull requests merged in 2025-04, with the labels that each got.

#3832 Further changes for nullability in the config package
  spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
  spring-kafka/src/main/java/org/springframework/kafka/config/ConcurrentKafkaListenerContainerFactory.java
  spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
  spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointAdapter.java
  spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
  spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsCustomizer.java
  spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java
  spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
  spring-kafka/src/main/java/org/springframework/kafka/support/JavaUtils.java
Labels: type: task

#3844 Add integration test for @Headers annotation
  spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Labels: type: improvement

#3842 Fix plural words
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
Labels: type: documentation
