Repository spring-projects/spring-kafka, pull requests merged in 2025-03, with the labels that each got.

#3779 Fix KafkaTemplate hiding exceptions when starting observation
  spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
Labels: type: bug, for: backport-to-3.2.x, for: backport-to-3.3.x

#3778 Handle null group id in listener observation
  spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaListenerObservation.java
  spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/KafkaListenerObservationTests.java
Labels: type: bug, for: backport-to-3.2.x, for: backport-to-3.3.x

#3811 GH-3810 Move the logging statement after the conditional statement.
  spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
Labels: type: enhancement, for: backport-to-3.2.x, for: backport-to-3.3.x

#3821 Adding whats-new section for 4.0.0
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
Labels: type: documentation

#3822 Update testing docs for 4.0.0 with the updates in EmbeddedKafka
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/quick-tour.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Labels: type: documentation

#3824 Fix typo document
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-annotation.adoc
  spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
Labels: type: documentation, for: backport-to-3.2.x, for: backport-to-3.3.x
